// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: llo_offchain_config.proto

package llo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLOOffchainConfigProto struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion                     uint32                 `protobuf:"varint,1,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	DefaultMinReportIntervalNanoseconds uint64                 `protobuf:"varint,2,opt,name=defaultMinReportIntervalNanoseconds,proto3" json:"defaultMinReportIntervalNanoseconds,omitempty"`
	EnableObservationCompression        bool                   `protobuf:"varint,3,opt,name=enableObservationCompression,proto3" json:"enableObservationCompression,omitempty"`
	EnableOutcomeCompression            bool                   `protobuf:"varint,4,opt,name=enableOutcomeCompression,proto3" json:"enableOutcomeCompression,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *LLOOffchainConfigProto) Reset() {
	*x = LLOOffchainConfigProto{}
	mi := &file_llo_offchain_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOOffchainConfigProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOOffchainConfigProto) ProtoMessage() {}

func (x *LLOOffchainConfigProto) ProtoReflect() protoreflect.Message {
	mi := &file_llo_offchain_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOOffchainConfigProto.ProtoReflect.Descriptor instead.
func (*LLOOffchainConfigProto) Descriptor() ([]byte, []int) {
	return file_llo_offchain_config_proto_rawDescGZIP(), []int{0}
}

func (x *LLOOffchainConfigProto) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *LLOOffchainConfigProto) GetDefaultMinReportIntervalNanoseconds() uint64 {
	if x != nil {
		return x.DefaultMinReportIntervalNanoseconds
	}
	return 0
}

func (x *LLOOffchainConfigProto) GetEnableObservationCompression() bool {
	if x != nil {
		return x.EnableObservationCompression
	}
	return false
}

func (x *LLOOffchainConfigProto) GetEnableOutcomeCompression() bool {
	if x != nil {
		return x.EnableOutcomeCompression
	}
	return false
}

var File_llo_offchain_config_proto protoreflect.FileDescriptor

const file_llo_offchain_config_proto_rawDesc = "" +
	"\n" +
	"\x19llo_offchain_config.proto\x12\x02v1\"\x94\x02\n" +
	"\x16LLOOffchainConfigProto\x12(\n" +
	"\x0fprotocolVersion\x18\x01 \x01(\rR\x0fprotocolVersion\x12P\n" +
	"#defaultMinReportIntervalNanoseconds\x18\x02 \x01(\x04R#defaultMinReportIntervalNanoseconds\x12B\n" +
	"\x1cenableObservationCompression\x18\x03 \x01(\bR\x1cenableObservationCompression\x12:\n" +
	"\x18enableOutcomeCompression\x18\x04 \x01(\bR\x18enableOutcomeCompressionB\aZ\x05.;llob\x06proto3"

var (
	file_llo_offchain_config_proto_rawDescOnce sync.Once
	file_llo_offchain_config_proto_rawDescData []byte
)

func file_llo_offchain_config_proto_rawDescGZIP() []byte {
	file_llo_offchain_config_proto_rawDescOnce.Do(func() {
		file_llo_offchain_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llo_offchain_config_proto_rawDesc), len(file_llo_offchain_config_proto_rawDesc)))
	})
	return file_llo_offchain_config_proto_rawDescData
}

var file_llo_offchain_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_llo_offchain_config_proto_goTypes = []any{
	(*LLOOffchainConfigProto)(nil), // 0: v1.LLOOffchainConfigProto
}
var file_llo_offchain_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llo_offchain_config_proto_init() }
func file_llo_offchain_config_proto_init() {
	if File_llo_offchain_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llo_offchain_config_proto_rawDesc), len(file_llo_offchain_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llo_offchain_config_proto_goTypes,
		DependencyIndexes: file_llo_offchain_config_proto_depIdxs,
		MessageInfos:      file_llo_offchain_config_proto_msgTypes,
	}.Build()
	File_llo_offchain_config_proto = out.File
	file_llo_offchain_config_proto_goTypes = nil
	file_llo_offchain_config_proto_depIdxs = nil
}
