// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: llo_plugin_telemetry.proto

package llo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LLOOutcomeTelemetry sent on every call to Outcome (once per
// round)
type LLOOutcomeTelemetry struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	LifeCycleStage                  string                 `protobuf:"bytes,1,opt,name=life_cycle_stage,json=lifeCycleStage,proto3" json:"life_cycle_stage,omitempty"`
	ObservationTimestampNanoseconds uint64                 `protobuf:"varint,2,opt,name=observation_timestamp_nanoseconds,json=observationTimestampNanoseconds,proto3" json:"observation_timestamp_nanoseconds,omitempty"`
	// channel id => channel definition
	ChannelDefinitions map[uint32]*LLOChannelDefinitionProto `protobuf:"bytes,3,rep,name=channel_definitions,json=channelDefinitions,proto3" json:"channel_definitions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// channel id => valid after nanoseconds
	ValidAfterNanoseconds map[uint32]uint64 `protobuf:"bytes,4,rep,name=valid_after_nanoseconds,json=validAfterNanoseconds,proto3" json:"valid_after_nanoseconds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// stream id => aggregator => value
	StreamAggregates map[uint32]*LLOAggregatorStreamValue `protobuf:"bytes,5,rep,name=stream_aggregates,json=streamAggregates,proto3" json:"stream_aggregates,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeqNr            uint64                               `protobuf:"varint,9,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	ConfigDigest     []byte                               `protobuf:"bytes,10,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	DonId            uint32                               `protobuf:"varint,11,opt,name=don_id,json=donId,proto3" json:"don_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLOOutcomeTelemetry) Reset() {
	*x = LLOOutcomeTelemetry{}
	mi := &file_llo_plugin_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOOutcomeTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOOutcomeTelemetry) ProtoMessage() {}

func (x *LLOOutcomeTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_llo_plugin_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOOutcomeTelemetry.ProtoReflect.Descriptor instead.
func (*LLOOutcomeTelemetry) Descriptor() ([]byte, []int) {
	return file_llo_plugin_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LLOOutcomeTelemetry) GetLifeCycleStage() string {
	if x != nil {
		return x.LifeCycleStage
	}
	return ""
}

func (x *LLOOutcomeTelemetry) GetObservationTimestampNanoseconds() uint64 {
	if x != nil {
		return x.ObservationTimestampNanoseconds
	}
	return 0
}

func (x *LLOOutcomeTelemetry) GetChannelDefinitions() map[uint32]*LLOChannelDefinitionProto {
	if x != nil {
		return x.ChannelDefinitions
	}
	return nil
}

func (x *LLOOutcomeTelemetry) GetValidAfterNanoseconds() map[uint32]uint64 {
	if x != nil {
		return x.ValidAfterNanoseconds
	}
	return nil
}

func (x *LLOOutcomeTelemetry) GetStreamAggregates() map[uint32]*LLOAggregatorStreamValue {
	if x != nil {
		return x.StreamAggregates
	}
	return nil
}

func (x *LLOOutcomeTelemetry) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *LLOOutcomeTelemetry) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *LLOOutcomeTelemetry) GetDonId() uint32 {
	if x != nil {
		return x.DonId
	}
	return 0
}

type LLOAggregatorStreamValue struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	AggregatorValues map[uint32]*LLOStreamValue `protobuf:"bytes,1,rep,name=aggregator_values,json=aggregatorValues,proto3" json:"aggregator_values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLOAggregatorStreamValue) Reset() {
	*x = LLOAggregatorStreamValue{}
	mi := &file_llo_plugin_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOAggregatorStreamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOAggregatorStreamValue) ProtoMessage() {}

func (x *LLOAggregatorStreamValue) ProtoReflect() protoreflect.Message {
	mi := &file_llo_plugin_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOAggregatorStreamValue.ProtoReflect.Descriptor instead.
func (*LLOAggregatorStreamValue) Descriptor() ([]byte, []int) {
	return file_llo_plugin_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *LLOAggregatorStreamValue) GetAggregatorValues() map[uint32]*LLOStreamValue {
	if x != nil {
		return x.AggregatorValues
	}
	return nil
}

// LLOReportTelemetry sent for each report on every call to Reports
type LLOReportTelemetry struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	ChannelId                       uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ValidAfterNanoseconds           uint64                 `protobuf:"varint,2,opt,name=valid_after_nanoseconds,json=validAfterNanoseconds,proto3" json:"valid_after_nanoseconds,omitempty"`
	ObservationTimestampNanoseconds uint64                 `protobuf:"varint,3,opt,name=observation_timestamp_nanoseconds,json=observationTimestampNanoseconds,proto3" json:"observation_timestamp_nanoseconds,omitempty"`
	ReportFormat                    uint32                 `protobuf:"varint,4,opt,name=report_format,json=reportFormat,proto3" json:"report_format,omitempty"`
	Specimen                        bool                   `protobuf:"varint,5,opt,name=specimen,proto3" json:"specimen,omitempty"`
	StreamDefinitions               []*LLOStreamDefinition `protobuf:"bytes,6,rep,name=stream_definitions,json=streamDefinitions,proto3" json:"stream_definitions,omitempty"`
	StreamValues                    []*LLOStreamValue      `protobuf:"bytes,7,rep,name=stream_values,json=streamValues,proto3" json:"stream_values,omitempty"`
	ChannelOpts                     []byte                 `protobuf:"bytes,8,opt,name=channel_opts,json=channelOpts,proto3" json:"channel_opts,omitempty"`
	SeqNr                           uint64                 `protobuf:"varint,9,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	ConfigDigest                    []byte                 `protobuf:"bytes,10,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	DonId                           uint32                 `protobuf:"varint,11,opt,name=don_id,json=donId,proto3" json:"don_id,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *LLOReportTelemetry) Reset() {
	*x = LLOReportTelemetry{}
	mi := &file_llo_plugin_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOReportTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOReportTelemetry) ProtoMessage() {}

func (x *LLOReportTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_llo_plugin_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOReportTelemetry.ProtoReflect.Descriptor instead.
func (*LLOReportTelemetry) Descriptor() ([]byte, []int) {
	return file_llo_plugin_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *LLOReportTelemetry) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *LLOReportTelemetry) GetValidAfterNanoseconds() uint64 {
	if x != nil {
		return x.ValidAfterNanoseconds
	}
	return 0
}

func (x *LLOReportTelemetry) GetObservationTimestampNanoseconds() uint64 {
	if x != nil {
		return x.ObservationTimestampNanoseconds
	}
	return 0
}

func (x *LLOReportTelemetry) GetReportFormat() uint32 {
	if x != nil {
		return x.ReportFormat
	}
	return 0
}

func (x *LLOReportTelemetry) GetSpecimen() bool {
	if x != nil {
		return x.Specimen
	}
	return false
}

func (x *LLOReportTelemetry) GetStreamDefinitions() []*LLOStreamDefinition {
	if x != nil {
		return x.StreamDefinitions
	}
	return nil
}

func (x *LLOReportTelemetry) GetStreamValues() []*LLOStreamValue {
	if x != nil {
		return x.StreamValues
	}
	return nil
}

func (x *LLOReportTelemetry) GetChannelOpts() []byte {
	if x != nil {
		return x.ChannelOpts
	}
	return nil
}

func (x *LLOReportTelemetry) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *LLOReportTelemetry) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *LLOReportTelemetry) GetDonId() uint32 {
	if x != nil {
		return x.DonId
	}
	return 0
}

var File_llo_plugin_telemetry_proto protoreflect.FileDescriptor

const file_llo_plugin_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1allo_plugin_telemetry.proto\x12\x02v1\x1a\x13plugin_codecs.proto\"\x9b\x06\n" +
	"\x13LLOOutcomeTelemetry\x12(\n" +
	"\x10life_cycle_stage\x18\x01 \x01(\tR\x0elifeCycleStage\x12J\n" +
	"!observation_timestamp_nanoseconds\x18\x02 \x01(\x04R\x1fobservationTimestampNanoseconds\x12`\n" +
	"\x13channel_definitions\x18\x03 \x03(\v2/.v1.LLOOutcomeTelemetry.ChannelDefinitionsEntryR\x12channelDefinitions\x12j\n" +
	"\x17valid_after_nanoseconds\x18\x04 \x03(\v22.v1.LLOOutcomeTelemetry.ValidAfterNanosecondsEntryR\x15validAfterNanoseconds\x12Z\n" +
	"\x11stream_aggregates\x18\x05 \x03(\v2-.v1.LLOOutcomeTelemetry.StreamAggregatesEntryR\x10streamAggregates\x12\x15\n" +
	"\x06seq_nr\x18\t \x01(\x04R\x05seqNr\x12#\n" +
	"\rconfig_digest\x18\n" +
	" \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06don_id\x18\v \x01(\rR\x05donId\x1ad\n" +
	"\x17ChannelDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.v1.LLOChannelDefinitionProtoR\x05value:\x028\x01\x1aH\n" +
	"\x1aValidAfterNanosecondsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aa\n" +
	"\x15StreamAggregatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.v1.LLOAggregatorStreamValueR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x18LLOAggregatorStreamValue\x12_\n" +
	"\x11aggregator_values\x18\x01 \x03(\v22.v1.LLOAggregatorStreamValue.AggregatorValuesEntryR\x10aggregatorValues\x1aW\n" +
	"\x15AggregatorValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.v1.LLOStreamValueR\x05value:\x028\x01\"\xef\x03\n" +
	"\x12LLOReportTelemetry\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x126\n" +
	"\x17valid_after_nanoseconds\x18\x02 \x01(\x04R\x15validAfterNanoseconds\x12J\n" +
	"!observation_timestamp_nanoseconds\x18\x03 \x01(\x04R\x1fobservationTimestampNanoseconds\x12#\n" +
	"\rreport_format\x18\x04 \x01(\rR\freportFormat\x12\x1a\n" +
	"\bspecimen\x18\x05 \x01(\bR\bspecimen\x12F\n" +
	"\x12stream_definitions\x18\x06 \x03(\v2\x17.v1.LLOStreamDefinitionR\x11streamDefinitions\x127\n" +
	"\rstream_values\x18\a \x03(\v2\x12.v1.LLOStreamValueR\fstreamValues\x12!\n" +
	"\fchannel_opts\x18\b \x01(\fR\vchannelOpts\x12\x15\n" +
	"\x06seq_nr\x18\t \x01(\x04R\x05seqNr\x12#\n" +
	"\rconfig_digest\x18\n" +
	" \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06don_id\x18\v \x01(\rR\x05donIdB\aZ\x05.;llob\x06proto3"

var (
	file_llo_plugin_telemetry_proto_rawDescOnce sync.Once
	file_llo_plugin_telemetry_proto_rawDescData []byte
)

func file_llo_plugin_telemetry_proto_rawDescGZIP() []byte {
	file_llo_plugin_telemetry_proto_rawDescOnce.Do(func() {
		file_llo_plugin_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llo_plugin_telemetry_proto_rawDesc), len(file_llo_plugin_telemetry_proto_rawDesc)))
	})
	return file_llo_plugin_telemetry_proto_rawDescData
}

var file_llo_plugin_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_llo_plugin_telemetry_proto_goTypes = []any{
	(*LLOOutcomeTelemetry)(nil),       // 0: v1.LLOOutcomeTelemetry
	(*LLOAggregatorStreamValue)(nil),  // 1: v1.LLOAggregatorStreamValue
	(*LLOReportTelemetry)(nil),        // 2: v1.LLOReportTelemetry
	nil,                               // 3: v1.LLOOutcomeTelemetry.ChannelDefinitionsEntry
	nil,                               // 4: v1.LLOOutcomeTelemetry.ValidAfterNanosecondsEntry
	nil,                               // 5: v1.LLOOutcomeTelemetry.StreamAggregatesEntry
	nil,                               // 6: v1.LLOAggregatorStreamValue.AggregatorValuesEntry
	(*LLOStreamDefinition)(nil),       // 7: v1.LLOStreamDefinition
	(*LLOStreamValue)(nil),            // 8: v1.LLOStreamValue
	(*LLOChannelDefinitionProto)(nil), // 9: v1.LLOChannelDefinitionProto
}
var file_llo_plugin_telemetry_proto_depIdxs = []int32{
	3, // 0: v1.LLOOutcomeTelemetry.channel_definitions:type_name -> v1.LLOOutcomeTelemetry.ChannelDefinitionsEntry
	4, // 1: v1.LLOOutcomeTelemetry.valid_after_nanoseconds:type_name -> v1.LLOOutcomeTelemetry.ValidAfterNanosecondsEntry
	5, // 2: v1.LLOOutcomeTelemetry.stream_aggregates:type_name -> v1.LLOOutcomeTelemetry.StreamAggregatesEntry
	6, // 3: v1.LLOAggregatorStreamValue.aggregator_values:type_name -> v1.LLOAggregatorStreamValue.AggregatorValuesEntry
	7, // 4: v1.LLOReportTelemetry.stream_definitions:type_name -> v1.LLOStreamDefinition
	8, // 5: v1.LLOReportTelemetry.stream_values:type_name -> v1.LLOStreamValue
	9, // 6: v1.LLOOutcomeTelemetry.ChannelDefinitionsEntry.value:type_name -> v1.LLOChannelDefinitionProto
	1, // 7: v1.LLOOutcomeTelemetry.StreamAggregatesEntry.value:type_name -> v1.LLOAggregatorStreamValue
	8, // 8: v1.LLOAggregatorStreamValue.AggregatorValuesEntry.value:type_name -> v1.LLOStreamValue
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_llo_plugin_telemetry_proto_init() }
func file_llo_plugin_telemetry_proto_init() {
	if File_llo_plugin_telemetry_proto != nil {
		return
	}
	file_plugin_codecs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llo_plugin_telemetry_proto_rawDesc), len(file_llo_plugin_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llo_plugin_telemetry_proto_goTypes,
		DependencyIndexes: file_llo_plugin_telemetry_proto_depIdxs,
		MessageInfos:      file_llo_plugin_telemetry_proto_msgTypes,
	}.Build()
	File_llo_plugin_telemetry_proto = out.File
	file_llo_plugin_telemetry_proto_goTypes = nil
	file_llo_plugin_telemetry_proto_depIdxs = nil
}
