// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: plugin_codecs.proto

package llo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLOStreamValue_Type int32

const (
	LLOStreamValue_Decimal                LLOStreamValue_Type = 0
	LLOStreamValue_Quote                  LLOStreamValue_Type = 1
	LLOStreamValue_TimestampedStreamValue LLOStreamValue_Type = 2
)

// Enum value maps for LLOStreamValue_Type.
var (
	LLOStreamValue_Type_name = map[int32]string{
		0: "Decimal",
		1: "Quote",
		2: "TimestampedStreamValue",
	}
	LLOStreamValue_Type_value = map[string]int32{
		"Decimal":                0,
		"Quote":                  1,
		"TimestampedStreamValue": 2,
	}
)

func (x LLOStreamValue_Type) Enum() *LLOStreamValue_Type {
	p := new(LLOStreamValue_Type)
	*p = x
	return p
}

func (x LLOStreamValue_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LLOStreamValue_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_codecs_proto_enumTypes[0].Descriptor()
}

func (LLOStreamValue_Type) Type() protoreflect.EnumType {
	return &file_plugin_codecs_proto_enumTypes[0]
}

func (x LLOStreamValue_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LLOStreamValue_Type.Descriptor instead.
func (LLOStreamValue_Type) EnumDescriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{1, 0}
}

// Observation CAN be changed as long as it doesn't break decode for legacy
// versions.
//
// i.e. adding new fields is ok
type LLOObservationProto struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	AttestedPredecessorRetirement []byte                 `protobuf:"bytes,1,opt,name=attestedPredecessorRetirement,proto3" json:"attestedPredecessorRetirement,omitempty"`
	ShouldRetire                  bool                   `protobuf:"varint,2,opt,name=shouldRetire,proto3" json:"shouldRetire,omitempty"`
	// TODO: unixTimestampNanosecondsLegacy can be removed after this version
	// is rolled out everywhere
	UnixTimestampNanosecondsLegacy int64    `protobuf:"varint,3,opt,name=unixTimestampNanosecondsLegacy,proto3" json:"unixTimestampNanosecondsLegacy,omitempty"`
	UnixTimestampNanoseconds       uint64   `protobuf:"varint,7,opt,name=unixTimestampNanoseconds,proto3" json:"unixTimestampNanoseconds,omitempty"`
	RemoveChannelIDs               []uint32 `protobuf:"varint,4,rep,packed,name=removeChannelIDs,proto3" json:"removeChannelIDs,omitempty"`
	// Maps are safe to use here because Observation serialization does not
	// need to be deterministic. Non-deterministic map serialization is
	// marginally more efficient than converting to tuples and guarantees
	// uniqueness.
	UpdateChannelDefinitions map[uint32]*LLOChannelDefinitionProto `protobuf:"bytes,5,rep,name=updateChannelDefinitions,proto3" json:"updateChannelDefinitions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamValues             map[uint32]*LLOStreamValue            `protobuf:"bytes,6,rep,name=streamValues,proto3" json:"streamValues,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LLOObservationProto) Reset() {
	*x = LLOObservationProto{}
	mi := &file_plugin_codecs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOObservationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOObservationProto) ProtoMessage() {}

func (x *LLOObservationProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOObservationProto.ProtoReflect.Descriptor instead.
func (*LLOObservationProto) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{0}
}

func (x *LLOObservationProto) GetAttestedPredecessorRetirement() []byte {
	if x != nil {
		return x.AttestedPredecessorRetirement
	}
	return nil
}

func (x *LLOObservationProto) GetShouldRetire() bool {
	if x != nil {
		return x.ShouldRetire
	}
	return false
}

func (x *LLOObservationProto) GetUnixTimestampNanosecondsLegacy() int64 {
	if x != nil {
		return x.UnixTimestampNanosecondsLegacy
	}
	return 0
}

func (x *LLOObservationProto) GetUnixTimestampNanoseconds() uint64 {
	if x != nil {
		return x.UnixTimestampNanoseconds
	}
	return 0
}

func (x *LLOObservationProto) GetRemoveChannelIDs() []uint32 {
	if x != nil {
		return x.RemoveChannelIDs
	}
	return nil
}

func (x *LLOObservationProto) GetUpdateChannelDefinitions() map[uint32]*LLOChannelDefinitionProto {
	if x != nil {
		return x.UpdateChannelDefinitions
	}
	return nil
}

func (x *LLOObservationProto) GetStreamValues() map[uint32]*LLOStreamValue {
	if x != nil {
		return x.StreamValues
	}
	return nil
}

type LLOStreamValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LLOStreamValue_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=v1.LLOStreamValue_Type" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOStreamValue) Reset() {
	*x = LLOStreamValue{}
	mi := &file_plugin_codecs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOStreamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOStreamValue) ProtoMessage() {}

func (x *LLOStreamValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOStreamValue.ProtoReflect.Descriptor instead.
func (*LLOStreamValue) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{1}
}

func (x *LLOStreamValue) GetType() LLOStreamValue_Type {
	if x != nil {
		return x.Type
	}
	return LLOStreamValue_Decimal
}

func (x *LLOStreamValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LLOStreamValueQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           []byte                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Benchmark     []byte                 `protobuf:"bytes,2,opt,name=benchmark,proto3" json:"benchmark,omitempty"`
	Ask           []byte                 `protobuf:"bytes,3,opt,name=ask,proto3" json:"ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOStreamValueQuote) Reset() {
	*x = LLOStreamValueQuote{}
	mi := &file_plugin_codecs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOStreamValueQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOStreamValueQuote) ProtoMessage() {}

func (x *LLOStreamValueQuote) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOStreamValueQuote.ProtoReflect.Descriptor instead.
func (*LLOStreamValueQuote) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{2}
}

func (x *LLOStreamValueQuote) GetBid() []byte {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *LLOStreamValueQuote) GetBenchmark() []byte {
	if x != nil {
		return x.Benchmark
	}
	return nil
}

func (x *LLOStreamValueQuote) GetAsk() []byte {
	if x != nil {
		return x.Ask
	}
	return nil
}

type LLOTimestampedStreamValue struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ObservedAtNanoseconds uint64                 `protobuf:"varint,1,opt,name=observedAtNanoseconds,proto3" json:"observedAtNanoseconds,omitempty"`
	StreamValue           *LLOStreamValue        `protobuf:"bytes,2,opt,name=streamValue,proto3" json:"streamValue,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LLOTimestampedStreamValue) Reset() {
	*x = LLOTimestampedStreamValue{}
	mi := &file_plugin_codecs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOTimestampedStreamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOTimestampedStreamValue) ProtoMessage() {}

func (x *LLOTimestampedStreamValue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOTimestampedStreamValue.ProtoReflect.Descriptor instead.
func (*LLOTimestampedStreamValue) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{3}
}

func (x *LLOTimestampedStreamValue) GetObservedAtNanoseconds() uint64 {
	if x != nil {
		return x.ObservedAtNanoseconds
	}
	return 0
}

func (x *LLOTimestampedStreamValue) GetStreamValue() *LLOStreamValue {
	if x != nil {
		return x.StreamValue
	}
	return nil
}

type LLOChannelDefinitionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportFormat  uint32                 `protobuf:"varint,1,opt,name=reportFormat,proto3" json:"reportFormat,omitempty"`
	Streams       []*LLOStreamDefinition `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	Opts          []byte                 `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOChannelDefinitionProto) Reset() {
	*x = LLOChannelDefinitionProto{}
	mi := &file_plugin_codecs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOChannelDefinitionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOChannelDefinitionProto) ProtoMessage() {}

func (x *LLOChannelDefinitionProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOChannelDefinitionProto.ProtoReflect.Descriptor instead.
func (*LLOChannelDefinitionProto) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{4}
}

func (x *LLOChannelDefinitionProto) GetReportFormat() uint32 {
	if x != nil {
		return x.ReportFormat
	}
	return 0
}

func (x *LLOChannelDefinitionProto) GetStreams() []*LLOStreamDefinition {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *LLOChannelDefinitionProto) GetOpts() []byte {
	if x != nil {
		return x.Opts
	}
	return nil
}

type LLOStreamDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamID      uint32                 `protobuf:"varint,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	Aggregator    uint32                 `protobuf:"varint,2,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOStreamDefinition) Reset() {
	*x = LLOStreamDefinition{}
	mi := &file_plugin_codecs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOStreamDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOStreamDefinition) ProtoMessage() {}

func (x *LLOStreamDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOStreamDefinition.ProtoReflect.Descriptor instead.
func (*LLOStreamDefinition) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{5}
}

func (x *LLOStreamDefinition) GetStreamID() uint32 {
	if x != nil {
		return x.StreamID
	}
	return 0
}

func (x *LLOStreamDefinition) GetAggregator() uint32 {
	if x != nil {
		return x.Aggregator
	}
	return 0
}

type LLOStreamObservationProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOStreamObservationProto) Reset() {
	*x = LLOStreamObservationProto{}
	mi := &file_plugin_codecs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOStreamObservationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOStreamObservationProto) ProtoMessage() {}

func (x *LLOStreamObservationProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOStreamObservationProto.ProtoReflect.Descriptor instead.
func (*LLOStreamObservationProto) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{6}
}

func (x *LLOStreamObservationProto) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *LLOStreamObservationProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// NOTE: Outcome must serialize deterministically, hence use of repeated tuple instead of maps
type LLOOutcomeProtoV0 struct {
	state                           protoimpl.MessageState                   `protogen:"open.v1"`
	LifeCycleStage                  string                                   `protobuf:"bytes,1,opt,name=lifeCycleStage,proto3" json:"lifeCycleStage,omitempty"`
	ObservationTimestampNanoseconds int64                                    `protobuf:"varint,2,opt,name=observationTimestampNanoseconds,proto3" json:"observationTimestampNanoseconds,omitempty"`
	ChannelDefinitions              []*LLOChannelIDAndDefinitionProto        `protobuf:"bytes,3,rep,name=channelDefinitions,proto3" json:"channelDefinitions,omitempty"`
	ValidAfterSeconds               []*LLOChannelIDAndValidAfterSecondsProto `protobuf:"bytes,4,rep,name=validAfterSeconds,proto3" json:"validAfterSeconds,omitempty"`
	StreamAggregates                []*LLOStreamAggregate                    `protobuf:"bytes,5,rep,name=streamAggregates,proto3" json:"streamAggregates,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *LLOOutcomeProtoV0) Reset() {
	*x = LLOOutcomeProtoV0{}
	mi := &file_plugin_codecs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOOutcomeProtoV0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOOutcomeProtoV0) ProtoMessage() {}

func (x *LLOOutcomeProtoV0) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOOutcomeProtoV0.ProtoReflect.Descriptor instead.
func (*LLOOutcomeProtoV0) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{7}
}

func (x *LLOOutcomeProtoV0) GetLifeCycleStage() string {
	if x != nil {
		return x.LifeCycleStage
	}
	return ""
}

func (x *LLOOutcomeProtoV0) GetObservationTimestampNanoseconds() int64 {
	if x != nil {
		return x.ObservationTimestampNanoseconds
	}
	return 0
}

func (x *LLOOutcomeProtoV0) GetChannelDefinitions() []*LLOChannelIDAndDefinitionProto {
	if x != nil {
		return x.ChannelDefinitions
	}
	return nil
}

func (x *LLOOutcomeProtoV0) GetValidAfterSeconds() []*LLOChannelIDAndValidAfterSecondsProto {
	if x != nil {
		return x.ValidAfterSeconds
	}
	return nil
}

func (x *LLOOutcomeProtoV0) GetStreamAggregates() []*LLOStreamAggregate {
	if x != nil {
		return x.StreamAggregates
	}
	return nil
}

// NOTE: Outcome must serialize deterministically, hence use of repeated tuple instead of maps
type LLOOutcomeProtoV1 struct {
	state                           protoimpl.MessageState                       `protogen:"open.v1"`
	LifeCycleStage                  string                                       `protobuf:"bytes,1,opt,name=lifeCycleStage,proto3" json:"lifeCycleStage,omitempty"`
	ObservationTimestampNanoseconds uint64                                       `protobuf:"varint,2,opt,name=observationTimestampNanoseconds,proto3" json:"observationTimestampNanoseconds,omitempty"`
	ChannelDefinitions              []*LLOChannelIDAndDefinitionProto            `protobuf:"bytes,3,rep,name=channelDefinitions,proto3" json:"channelDefinitions,omitempty"`
	ValidAfterNanoseconds           []*LLOChannelIDAndValidAfterNanosecondsProto `protobuf:"bytes,4,rep,name=validAfterNanoseconds,proto3" json:"validAfterNanoseconds,omitempty"`
	StreamAggregates                []*LLOStreamAggregate                        `protobuf:"bytes,5,rep,name=streamAggregates,proto3" json:"streamAggregates,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *LLOOutcomeProtoV1) Reset() {
	*x = LLOOutcomeProtoV1{}
	mi := &file_plugin_codecs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOOutcomeProtoV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOOutcomeProtoV1) ProtoMessage() {}

func (x *LLOOutcomeProtoV1) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOOutcomeProtoV1.ProtoReflect.Descriptor instead.
func (*LLOOutcomeProtoV1) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{8}
}

func (x *LLOOutcomeProtoV1) GetLifeCycleStage() string {
	if x != nil {
		return x.LifeCycleStage
	}
	return ""
}

func (x *LLOOutcomeProtoV1) GetObservationTimestampNanoseconds() uint64 {
	if x != nil {
		return x.ObservationTimestampNanoseconds
	}
	return 0
}

func (x *LLOOutcomeProtoV1) GetChannelDefinitions() []*LLOChannelIDAndDefinitionProto {
	if x != nil {
		return x.ChannelDefinitions
	}
	return nil
}

func (x *LLOOutcomeProtoV1) GetValidAfterNanoseconds() []*LLOChannelIDAndValidAfterNanosecondsProto {
	if x != nil {
		return x.ValidAfterNanoseconds
	}
	return nil
}

func (x *LLOOutcomeProtoV1) GetStreamAggregates() []*LLOStreamAggregate {
	if x != nil {
		return x.StreamAggregates
	}
	return nil
}

type LLOChannelIDAndDefinitionProto struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	ChannelID         uint32                     `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	ChannelDefinition *LLOChannelDefinitionProto `protobuf:"bytes,2,opt,name=channelDefinition,proto3" json:"channelDefinition,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLOChannelIDAndDefinitionProto) Reset() {
	*x = LLOChannelIDAndDefinitionProto{}
	mi := &file_plugin_codecs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOChannelIDAndDefinitionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOChannelIDAndDefinitionProto) ProtoMessage() {}

func (x *LLOChannelIDAndDefinitionProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOChannelIDAndDefinitionProto.ProtoReflect.Descriptor instead.
func (*LLOChannelIDAndDefinitionProto) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{9}
}

func (x *LLOChannelIDAndDefinitionProto) GetChannelID() uint32 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

func (x *LLOChannelIDAndDefinitionProto) GetChannelDefinition() *LLOChannelDefinitionProto {
	if x != nil {
		return x.ChannelDefinition
	}
	return nil
}

type LLOChannelIDAndValidAfterSecondsProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChannelID         uint32                 `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	ValidAfterSeconds uint32                 `protobuf:"varint,2,opt,name=validAfterSeconds,proto3" json:"validAfterSeconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLOChannelIDAndValidAfterSecondsProto) Reset() {
	*x = LLOChannelIDAndValidAfterSecondsProto{}
	mi := &file_plugin_codecs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOChannelIDAndValidAfterSecondsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOChannelIDAndValidAfterSecondsProto) ProtoMessage() {}

func (x *LLOChannelIDAndValidAfterSecondsProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOChannelIDAndValidAfterSecondsProto.ProtoReflect.Descriptor instead.
func (*LLOChannelIDAndValidAfterSecondsProto) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{10}
}

func (x *LLOChannelIDAndValidAfterSecondsProto) GetChannelID() uint32 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

func (x *LLOChannelIDAndValidAfterSecondsProto) GetValidAfterSeconds() uint32 {
	if x != nil {
		return x.ValidAfterSeconds
	}
	return 0
}

type LLOChannelIDAndValidAfterNanosecondsProto struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChannelID             uint32                 `protobuf:"varint,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	ValidAfterNanoseconds uint64                 `protobuf:"varint,2,opt,name=validAfterNanoseconds,proto3" json:"validAfterNanoseconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LLOChannelIDAndValidAfterNanosecondsProto) Reset() {
	*x = LLOChannelIDAndValidAfterNanosecondsProto{}
	mi := &file_plugin_codecs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOChannelIDAndValidAfterNanosecondsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOChannelIDAndValidAfterNanosecondsProto) ProtoMessage() {}

func (x *LLOChannelIDAndValidAfterNanosecondsProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOChannelIDAndValidAfterNanosecondsProto.ProtoReflect.Descriptor instead.
func (*LLOChannelIDAndValidAfterNanosecondsProto) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{11}
}

func (x *LLOChannelIDAndValidAfterNanosecondsProto) GetChannelID() uint32 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

func (x *LLOChannelIDAndValidAfterNanosecondsProto) GetValidAfterNanoseconds() uint64 {
	if x != nil {
		return x.ValidAfterNanoseconds
	}
	return 0
}

type LLOStreamAggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamID      uint32                 `protobuf:"varint,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	StreamValue   *LLOStreamValue        `protobuf:"bytes,2,opt,name=streamValue,proto3" json:"streamValue,omitempty"`
	Aggregator    uint32                 `protobuf:"varint,3,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOStreamAggregate) Reset() {
	*x = LLOStreamAggregate{}
	mi := &file_plugin_codecs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOStreamAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOStreamAggregate) ProtoMessage() {}

func (x *LLOStreamAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_codecs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOStreamAggregate.ProtoReflect.Descriptor instead.
func (*LLOStreamAggregate) Descriptor() ([]byte, []int) {
	return file_plugin_codecs_proto_rawDescGZIP(), []int{12}
}

func (x *LLOStreamAggregate) GetStreamID() uint32 {
	if x != nil {
		return x.StreamID
	}
	return 0
}

func (x *LLOStreamAggregate) GetStreamValue() *LLOStreamValue {
	if x != nil {
		return x.StreamValue
	}
	return nil
}

func (x *LLOStreamAggregate) GetAggregator() uint32 {
	if x != nil {
		return x.Aggregator
	}
	return 0
}

var File_plugin_codecs_proto protoreflect.FileDescriptor

const file_plugin_codecs_proto_rawDesc = "" +
	"\n" +
	"\x13plugin_codecs.proto\x12\x02v1\"\xb2\x05\n" +
	"\x13LLOObservationProto\x12D\n" +
	"\x1dattestedPredecessorRetirement\x18\x01 \x01(\fR\x1dattestedPredecessorRetirement\x12\"\n" +
	"\fshouldRetire\x18\x02 \x01(\bR\fshouldRetire\x12F\n" +
	"\x1eunixTimestampNanosecondsLegacy\x18\x03 \x01(\x03R\x1eunixTimestampNanosecondsLegacy\x12:\n" +
	"\x18unixTimestampNanoseconds\x18\a \x01(\x04R\x18unixTimestampNanoseconds\x12*\n" +
	"\x10removeChannelIDs\x18\x04 \x03(\rR\x10removeChannelIDs\x12q\n" +
	"\x18updateChannelDefinitions\x18\x05 \x03(\v25.v1.LLOObservationProto.UpdateChannelDefinitionsEntryR\x18updateChannelDefinitions\x12M\n" +
	"\fstreamValues\x18\x06 \x03(\v2).v1.LLOObservationProto.StreamValuesEntryR\fstreamValues\x1aj\n" +
	"\x1dUpdateChannelDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.v1.LLOChannelDefinitionProtoR\x05value:\x028\x01\x1aS\n" +
	"\x11StreamValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.v1.LLOStreamValueR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x0eLLOStreamValue\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.v1.LLOStreamValue.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\":\n" +
	"\x04Type\x12\v\n" +
	"\aDecimal\x10\x00\x12\t\n" +
	"\x05Quote\x10\x01\x12\x1a\n" +
	"\x16TimestampedStreamValue\x10\x02\"W\n" +
	"\x13LLOStreamValueQuote\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\fR\x03bid\x12\x1c\n" +
	"\tbenchmark\x18\x02 \x01(\fR\tbenchmark\x12\x10\n" +
	"\x03ask\x18\x03 \x01(\fR\x03ask\"\x87\x01\n" +
	"\x19LLOTimestampedStreamValue\x124\n" +
	"\x15observedAtNanoseconds\x18\x01 \x01(\x04R\x15observedAtNanoseconds\x124\n" +
	"\vstreamValue\x18\x02 \x01(\v2\x12.v1.LLOStreamValueR\vstreamValue\"\x86\x01\n" +
	"\x19LLOChannelDefinitionProto\x12\"\n" +
	"\freportFormat\x18\x01 \x01(\rR\freportFormat\x121\n" +
	"\astreams\x18\x02 \x03(\v2\x17.v1.LLOStreamDefinitionR\astreams\x12\x12\n" +
	"\x04opts\x18\x03 \x01(\fR\x04opts\"Q\n" +
	"\x13LLOStreamDefinition\x12\x1a\n" +
	"\bstreamID\x18\x01 \x01(\rR\bstreamID\x12\x1e\n" +
	"\n" +
	"aggregator\x18\x02 \x01(\rR\n" +
	"aggregator\"G\n" +
	"\x19LLOStreamObservationProto\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xf6\x02\n" +
	"\x11LLOOutcomeProtoV0\x12&\n" +
	"\x0elifeCycleStage\x18\x01 \x01(\tR\x0elifeCycleStage\x12H\n" +
	"\x1fobservationTimestampNanoseconds\x18\x02 \x01(\x03R\x1fobservationTimestampNanoseconds\x12R\n" +
	"\x12channelDefinitions\x18\x03 \x03(\v2\".v1.LLOChannelIDAndDefinitionProtoR\x12channelDefinitions\x12W\n" +
	"\x11validAfterSeconds\x18\x04 \x03(\v2).v1.LLOChannelIDAndValidAfterSecondsProtoR\x11validAfterSeconds\x12B\n" +
	"\x10streamAggregates\x18\x05 \x03(\v2\x16.v1.LLOStreamAggregateR\x10streamAggregates\"\x82\x03\n" +
	"\x11LLOOutcomeProtoV1\x12&\n" +
	"\x0elifeCycleStage\x18\x01 \x01(\tR\x0elifeCycleStage\x12H\n" +
	"\x1fobservationTimestampNanoseconds\x18\x02 \x01(\x04R\x1fobservationTimestampNanoseconds\x12R\n" +
	"\x12channelDefinitions\x18\x03 \x03(\v2\".v1.LLOChannelIDAndDefinitionProtoR\x12channelDefinitions\x12c\n" +
	"\x15validAfterNanoseconds\x18\x04 \x03(\v2-.v1.LLOChannelIDAndValidAfterNanosecondsProtoR\x15validAfterNanoseconds\x12B\n" +
	"\x10streamAggregates\x18\x05 \x03(\v2\x16.v1.LLOStreamAggregateR\x10streamAggregates\"\x8b\x01\n" +
	"\x1eLLOChannelIDAndDefinitionProto\x12\x1c\n" +
	"\tchannelID\x18\x01 \x01(\rR\tchannelID\x12K\n" +
	"\x11channelDefinition\x18\x02 \x01(\v2\x1d.v1.LLOChannelDefinitionProtoR\x11channelDefinition\"s\n" +
	"%LLOChannelIDAndValidAfterSecondsProto\x12\x1c\n" +
	"\tchannelID\x18\x01 \x01(\rR\tchannelID\x12,\n" +
	"\x11validAfterSeconds\x18\x02 \x01(\rR\x11validAfterSeconds\"\x7f\n" +
	")LLOChannelIDAndValidAfterNanosecondsProto\x12\x1c\n" +
	"\tchannelID\x18\x01 \x01(\rR\tchannelID\x124\n" +
	"\x15validAfterNanoseconds\x18\x02 \x01(\x04R\x15validAfterNanoseconds\"\x86\x01\n" +
	"\x12LLOStreamAggregate\x12\x1a\n" +
	"\bstreamID\x18\x01 \x01(\rR\bstreamID\x124\n" +
	"\vstreamValue\x18\x02 \x01(\v2\x12.v1.LLOStreamValueR\vstreamValue\x12\x1e\n" +
	"\n" +
	"aggregator\x18\x03 \x01(\rR\n" +
	"aggregatorB\aZ\x05.;llob\x06proto3"

var (
	file_plugin_codecs_proto_rawDescOnce sync.Once
	file_plugin_codecs_proto_rawDescData []byte
)

func file_plugin_codecs_proto_rawDescGZIP() []byte {
	file_plugin_codecs_proto_rawDescOnce.Do(func() {
		file_plugin_codecs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_codecs_proto_rawDesc), len(file_plugin_codecs_proto_rawDesc)))
	})
	return file_plugin_codecs_proto_rawDescData
}

var file_plugin_codecs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_codecs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_plugin_codecs_proto_goTypes = []any{
	(LLOStreamValue_Type)(0),                          // 0: v1.LLOStreamValue.Type
	(*LLOObservationProto)(nil),                       // 1: v1.LLOObservationProto
	(*LLOStreamValue)(nil),                            // 2: v1.LLOStreamValue
	(*LLOStreamValueQuote)(nil),                       // 3: v1.LLOStreamValueQuote
	(*LLOTimestampedStreamValue)(nil),                 // 4: v1.LLOTimestampedStreamValue
	(*LLOChannelDefinitionProto)(nil),                 // 5: v1.LLOChannelDefinitionProto
	(*LLOStreamDefinition)(nil),                       // 6: v1.LLOStreamDefinition
	(*LLOStreamObservationProto)(nil),                 // 7: v1.LLOStreamObservationProto
	(*LLOOutcomeProtoV0)(nil),                         // 8: v1.LLOOutcomeProtoV0
	(*LLOOutcomeProtoV1)(nil),                         // 9: v1.LLOOutcomeProtoV1
	(*LLOChannelIDAndDefinitionProto)(nil),            // 10: v1.LLOChannelIDAndDefinitionProto
	(*LLOChannelIDAndValidAfterSecondsProto)(nil),     // 11: v1.LLOChannelIDAndValidAfterSecondsProto
	(*LLOChannelIDAndValidAfterNanosecondsProto)(nil), // 12: v1.LLOChannelIDAndValidAfterNanosecondsProto
	(*LLOStreamAggregate)(nil),                        // 13: v1.LLOStreamAggregate
	nil,                                               // 14: v1.LLOObservationProto.UpdateChannelDefinitionsEntry
	nil,                                               // 15: v1.LLOObservationProto.StreamValuesEntry
}
var file_plugin_codecs_proto_depIdxs = []int32{
	14, // 0: v1.LLOObservationProto.updateChannelDefinitions:type_name -> v1.LLOObservationProto.UpdateChannelDefinitionsEntry
	15, // 1: v1.LLOObservationProto.streamValues:type_name -> v1.LLOObservationProto.StreamValuesEntry
	0,  // 2: v1.LLOStreamValue.type:type_name -> v1.LLOStreamValue.Type
	2,  // 3: v1.LLOTimestampedStreamValue.streamValue:type_name -> v1.LLOStreamValue
	6,  // 4: v1.LLOChannelDefinitionProto.streams:type_name -> v1.LLOStreamDefinition
	10, // 5: v1.LLOOutcomeProtoV0.channelDefinitions:type_name -> v1.LLOChannelIDAndDefinitionProto
	11, // 6: v1.LLOOutcomeProtoV0.validAfterSeconds:type_name -> v1.LLOChannelIDAndValidAfterSecondsProto
	13, // 7: v1.LLOOutcomeProtoV0.streamAggregates:type_name -> v1.LLOStreamAggregate
	10, // 8: v1.LLOOutcomeProtoV1.channelDefinitions:type_name -> v1.LLOChannelIDAndDefinitionProto
	12, // 9: v1.LLOOutcomeProtoV1.validAfterNanoseconds:type_name -> v1.LLOChannelIDAndValidAfterNanosecondsProto
	13, // 10: v1.LLOOutcomeProtoV1.streamAggregates:type_name -> v1.LLOStreamAggregate
	5,  // 11: v1.LLOChannelIDAndDefinitionProto.channelDefinition:type_name -> v1.LLOChannelDefinitionProto
	2,  // 12: v1.LLOStreamAggregate.streamValue:type_name -> v1.LLOStreamValue
	5,  // 13: v1.LLOObservationProto.UpdateChannelDefinitionsEntry.value:type_name -> v1.LLOChannelDefinitionProto
	2,  // 14: v1.LLOObservationProto.StreamValuesEntry.value:type_name -> v1.LLOStreamValue
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_plugin_codecs_proto_init() }
func file_plugin_codecs_proto_init() {
	if File_plugin_codecs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_codecs_proto_rawDesc), len(file_plugin_codecs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_codecs_proto_goTypes,
		DependencyIndexes: file_plugin_codecs_proto_depIdxs,
		EnumInfos:         file_plugin_codecs_proto_enumTypes,
		MessageInfos:      file_plugin_codecs_proto_msgTypes,
	}.Build()
	File_plugin_codecs_proto = out.File
	file_plugin_codecs_proto_goTypes = nil
	file_plugin_codecs_proto_depIdxs = nil
}
