// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: evm_streamlined.proto

package evm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLOEVMStreamlinedReportWithContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest  []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	SeqNr         uint64                 `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	PackedPayload []byte                 `protobuf:"bytes,3,opt,name=packed_payload,json=packedPayload,proto3" json:"packed_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLOEVMStreamlinedReportWithContext) Reset() {
	*x = LLOEVMStreamlinedReportWithContext{}
	mi := &file_evm_streamlined_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLOEVMStreamlinedReportWithContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLOEVMStreamlinedReportWithContext) ProtoMessage() {}

func (x *LLOEVMStreamlinedReportWithContext) ProtoReflect() protoreflect.Message {
	mi := &file_evm_streamlined_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLOEVMStreamlinedReportWithContext.ProtoReflect.Descriptor instead.
func (*LLOEVMStreamlinedReportWithContext) Descriptor() ([]byte, []int) {
	return file_evm_streamlined_proto_rawDescGZIP(), []int{0}
}

func (x *LLOEVMStreamlinedReportWithContext) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *LLOEVMStreamlinedReportWithContext) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *LLOEVMStreamlinedReportWithContext) GetPackedPayload() []byte {
	if x != nil {
		return x.PackedPayload
	}
	return nil
}

var File_evm_streamlined_proto protoreflect.FileDescriptor

const file_evm_streamlined_proto_rawDesc = "" +
	"\n" +
	"\x15evm_streamlined.proto\x12\x03evm\"\x87\x01\n" +
	"\"LLOEVMStreamlinedReportWithContext\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x04R\x05seqNr\x12%\n" +
	"\x0epacked_payload\x18\x03 \x01(\fR\rpackedPayloadBLZJgithub.com/smartcontractkit/chainlink-data-streams/llo/reportcodec/evm;evmb\x06proto3"

var (
	file_evm_streamlined_proto_rawDescOnce sync.Once
	file_evm_streamlined_proto_rawDescData []byte
)

func file_evm_streamlined_proto_rawDescGZIP() []byte {
	file_evm_streamlined_proto_rawDescOnce.Do(func() {
		file_evm_streamlined_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evm_streamlined_proto_rawDesc), len(file_evm_streamlined_proto_rawDesc)))
	})
	return file_evm_streamlined_proto_rawDescData
}

var file_evm_streamlined_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_evm_streamlined_proto_goTypes = []any{
	(*LLOEVMStreamlinedReportWithContext)(nil), // 0: evm.LLOEVMStreamlinedReportWithContext
}
var file_evm_streamlined_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evm_streamlined_proto_init() }
func file_evm_streamlined_proto_init() {
	if File_evm_streamlined_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evm_streamlined_proto_rawDesc), len(file_evm_streamlined_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evm_streamlined_proto_goTypes,
		DependencyIndexes: file_evm_streamlined_proto_depIdxs,
		MessageInfos:      file_evm_streamlined_proto_msgTypes,
	}.Build()
	File_evm_streamlined_proto = out.File
	file_evm_streamlined_proto_goTypes = nil
	file_evm_streamlined_proto_depIdxs = nil
}
