// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: attested_retirement_report.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestedRetirementReport struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	RetirementReport []byte                        `protobuf:"bytes,1,opt,name=retirementReport,proto3" json:"retirementReport,omitempty"`
	SeqNr            uint64                        `protobuf:"varint,2,opt,name=seqNr,proto3" json:"seqNr,omitempty"`
	Sigs             []*AttributedOnchainSignature `protobuf:"bytes,3,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttestedRetirementReport) Reset() {
	*x = AttestedRetirementReport{}
	mi := &file_attested_retirement_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRetirementReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRetirementReport) ProtoMessage() {}

func (x *AttestedRetirementReport) ProtoReflect() protoreflect.Message {
	mi := &file_attested_retirement_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRetirementReport.ProtoReflect.Descriptor instead.
func (*AttestedRetirementReport) Descriptor() ([]byte, []int) {
	return file_attested_retirement_report_proto_rawDescGZIP(), []int{0}
}

func (x *AttestedRetirementReport) GetRetirementReport() []byte {
	if x != nil {
		return x.RetirementReport
	}
	return nil
}

func (x *AttestedRetirementReport) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *AttestedRetirementReport) GetSigs() []*AttributedOnchainSignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type AttributedOnchainSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Signer        uint32                 `protobuf:"varint,2,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedOnchainSignature) Reset() {
	*x = AttributedOnchainSignature{}
	mi := &file_attested_retirement_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedOnchainSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedOnchainSignature) ProtoMessage() {}

func (x *AttributedOnchainSignature) ProtoReflect() protoreflect.Message {
	mi := &file_attested_retirement_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedOnchainSignature.ProtoReflect.Descriptor instead.
func (*AttributedOnchainSignature) Descriptor() ([]byte, []int) {
	return file_attested_retirement_report_proto_rawDescGZIP(), []int{1}
}

func (x *AttributedOnchainSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AttributedOnchainSignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

var File_attested_retirement_report_proto protoreflect.FileDescriptor

const file_attested_retirement_report_proto_rawDesc = "" +
	"\n" +
	" attested_retirement_report.proto\x12\n" +
	"retirement\"\x98\x01\n" +
	"\x18AttestedRetirementReport\x12*\n" +
	"\x10retirementReport\x18\x01 \x01(\fR\x10retirementReport\x12\x14\n" +
	"\x05seqNr\x18\x02 \x01(\x04R\x05seqNr\x12:\n" +
	"\x04sigs\x18\x03 \x03(\v2&.retirement.AttributedOnchainSignatureR\x04sigs\"R\n" +
	"\x1aAttributedOnchainSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x16\n" +
	"\x06signer\x18\x02 \x01(\rR\x06signerBJZHgithub.com/smartcontractkit/chainlink-data-streams/llo/protocol;protocolb\x06proto3"

var (
	file_attested_retirement_report_proto_rawDescOnce sync.Once
	file_attested_retirement_report_proto_rawDescData []byte
)

func file_attested_retirement_report_proto_rawDescGZIP() []byte {
	file_attested_retirement_report_proto_rawDescOnce.Do(func() {
		file_attested_retirement_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attested_retirement_report_proto_rawDesc), len(file_attested_retirement_report_proto_rawDesc)))
	})
	return file_attested_retirement_report_proto_rawDescData
}

var file_attested_retirement_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_attested_retirement_report_proto_goTypes = []any{
	(*AttestedRetirementReport)(nil),   // 0: retirement.AttestedRetirementReport
	(*AttributedOnchainSignature)(nil), // 1: retirement.AttributedOnchainSignature
}
var file_attested_retirement_report_proto_depIdxs = []int32{
	1, // 0: retirement.AttestedRetirementReport.sigs:type_name -> retirement.AttributedOnchainSignature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_attested_retirement_report_proto_init() }
func file_attested_retirement_report_proto_init() {
	if File_attested_retirement_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attested_retirement_report_proto_rawDesc), len(file_attested_retirement_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attested_retirement_report_proto_goTypes,
		DependencyIndexes: file_attested_retirement_report_proto_depIdxs,
		MessageInfos:      file_attested_retirement_report_proto_msgTypes,
	}.Build()
	File_attested_retirement_report_proto = out.File
	file_attested_retirement_report_proto_goTypes = nil
	file_attested_retirement_report_proto_depIdxs = nil
}
