name: pull-request-master

on:
  merge_group:
  pull_request:
    branches:
      - master
# Only run 1 of this workflow at a time per PR
concurrency:
  group: chainlink-data-streams-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGES: "mercury"

jobs:
  env:
    # We explicitly have this env var not be "CL_DATABASE_URL" to avoid having it be used by core related tests
    # when they should not be using it, while still allowing us to DRY up the setup
    DB_URL: postgresql://postgres:postgres@localhost:5432/chainlink_test?sslmode=disable

  init:
    runs-on: ubuntu-latest
    outputs:
      matrix_packages: ${{ steps.set-matrix-packages.outputs.matrix_packages }}
      lint_args_packages: ${{ steps.set-matrix-packages.outputs.lint_args_packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
      - name: Set matrix packages
        id: set-matrix-packages
        shell: bash
        env:
          PACKAGES: ${{ env.PACKAGES }}
        run: |
          matrix_packages=$(echo "${PACKAGES}" | jq -R 'split(",")' | tr -d "\n\t")
          echo "matrix_packages=${matrix_packages}" | tee -a "${GITHUB_OUTPUT}"
      - name: Set lint args packages
        id: set-lint-args-packages
        shell: bash
        env:
          PACKAGES: ${{ env.PACKAGES }}
        run: echo "lint_args_packages=$(echo "./$(echo $PACKAGES | sed 's/,/\/... .\//g;s/$/\/.../')")" | tee -a "${GITHUB_OUTPUT}"

  ci-lint:
    runs-on: ubuntu-latest
    needs: [init]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-lint
        uses: smartcontractkit/.github/actions/ci-lint-go@944f2dce535bee4b9bf9677b6983d8a3b78111bf
        with:
          # env inputs
          use-env-files: "true"
          env-files: ./tools/env/ci.env
          # go inputs
          use-go-cache: true
          go-cache-dep-path: "**/go.sum"
          go-version-file: go.mod
          golangci-lint-version: "latest"

  ci-lint-misc:
    runs-on: ubuntu-latest
    steps:
      - name: ci-lint-misc
        uses: smartcontractkit/.github/actions/ci-lint-misc@944f2dce535bee4b9bf9677b6983d8a3b78111bf

  ci-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build
        run: go build ./...

      - name: Setup Postgres
        uses: smartcontractkit/.github/actions/setup-postgres@7aa7ce23687ba493e9ba9c6ad47a063e60ae3433 # setup-postgres@0.1.0

      - name: Setup DB
        run: make testdb
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}

      - name: Unit Tests
        run: GORACE="log_path=$PWD/race" go test -race ./... -coverpkg=./... -coverprofile=coverage.txt
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}

      - name: Upload Go test results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: go-test-results
          path: |
            ./coverage.txt
            ./race.*

  ci-sonarqube:
    needs: [ci-lint, ci-test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: ci-sonarqube
        uses: smartcontractkit/.github/actions/ci-sonarqube-go@3e11dbc45e4c8b18dd996fb417ccf22056176388 # ci-sonarqube-go@0.1.0
        with:
          # sonarqube inputs
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
